name: Container Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: (Optional) Docker Hub login
      # Uncomment if you need to push the image to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t nodeapp:latest .

      # Step 4: (Optional) Run Docker Scout analysis
      # Uncomment if you want to include Docker Scout for further image analysis
      # - name: Docker Scout
      #   id: docker-scout
      #   uses: docker/scout-action@v1
      #   with:
      #     command: quickview,cves,sbom
      #     image: "nodeapp:latest"
      #     ignore-unchanged: true
      #     only-severities: critical,high
      #     summary: true
      #     write-comment: false

      # Step 5: Cache Trivy database to improve performance
      - name: Cache Trivy DB
        id: trivy-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ github.sha }}

      # Step 6: Run Trivy vulnerability scanner only if cache is not hit
      - name: Run Trivy vulnerability scanner
        if: steps.trivy-cache.outputs.cache-hit != 'true'
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'nodeapp:latest'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH'
          format: table
          output: trivy.txt
          cache-dir: /tmp/.cache/trivy

      # Step 7: Publish Trivy vulnerability scan report to the GitHub summary
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
