name: Container Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Uncomment to log in to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nodeapp:latest .

      # Uncomment to run Docker Scout
      # - name: Docker Scout
      #   id: docker-scout
      #   uses: docker/scout-action@v1
      #   with:
      #     command: quickview,cves,sbom
      #     image: "nodeapp:latest"
      #     ignore-unchanged: true
      #     only-severities: critical,high
      #     summary: true
      #     write-comment: false

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'nodeapp:latest'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH'
          format: template
          template: "@trivy/github-markdown.tpl"
          output: ${{ github.step_summary }}

