name: Container Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: (Optional) Docker Hub login
      # Uncomment if you need to push the image to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t nodeapp:latest .

      # Step 4: Create cache directory for Trivy
      - name: Create Trivy cache directory
        run: mkdir -p ${{ github.workspace }}/.cache/trivy

      # Step 5: Run Trivy vulnerability scanner with caching
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.24.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2

        with:
          image-ref: 'nodeapp:latest'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH'
          format: table
          output: trivy.txt
         


      # Step 7: Publish Trivy vulnerability scan report to the GitHub summary
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```plaintext'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
