name: Container Image CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build 
      #   run: docker build -t nodeapp:latest .

      # - name: Docker Scout
      #   id: docker-scout
      #   uses: docker/scout-action@v1
      #   with:
      #     command: quickview,cves,sbom
      #     image: "nodeapp:latest"
      #     ignore-unchanged: true
      #     only-severities: critical,high
      #     summary: true
      #     write-comment: false

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'nodeapp:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH'
          output: './trivy-results.txt'

      - name: Read Trivy output and format as markdown
        run: |
          echo "### Trivy Vulnerabilities Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "| Vulnerability | Package | Severity | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|---------|----------|-------------|" >> $GITHUB_STEP_SUMMARY
          grep -A 4 -E "^Total Vulnerabilities:|^\w+ \[.*\]" ./trivy-results.txt | awk '{
              if($1 ~ /^[a-zA-Z0-9]/) 
                  printf("| %s | %s | %s | %s |\n", $1, $3, $NF, $0);
          }' >> $GITHUB_STEP_SUMMARY

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "nodeapp:latest"
          fail-build: false
          output-format: table
