name: Container Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      - run: mkdir oci && tar -C oci -xf ${{ github.sha }}.tar
      - uses: aquasecurity/trivy-action@master
        with:
          input: oci
          format: template
          template: "@trivy/github-markdown.tpl"
          output: trivy.md
          security-checks: vuln
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 1
      - run: cat trivy.md >> $GITHUB_STEP_SUMMARY
        if: always()
