name: Container Image CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build 
        run: docker build -t nodeapp:latest .

      # - name: Docker Scout
      #   id: docker-scout
      #   uses: docker/scout-action@v1
      #   with:
      #     command: quickview,cves,sbom
      #     image: "nodeapp:latest"
      #     ignore-unchanged: true
      #     only-severities: critical,high
      #     summary: true
      #     write-comment: false

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'nodeapp:latest'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'HIGH'
          format: template
          template: "@/contrib/html.tpl"
          output: trivy-report.html

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.html

      - name: Add Trivy report to summary
        run: echo '### Vulnerability Report 📄\n\n[Trivy Report](./trivy-report.html)' >> $GITHUB_STEP_SUMMARY
